package io.github.maritims.advent_of_code.year_eleven;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.stream.Collectors;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.spy;

class Day7Test {
    Day7 sut;

    @BeforeEach
    void setUp() {
        sut = spy(new Day7());
    }

    @Test
    void solveFirstPart_withSampleInput() {
        doReturn(Arrays.stream("""
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """.split("\n")).collect(Collectors.toCollection(ArrayList::new))).when(sut).loadInput();
        assertEquals(21, sut.solveFirstPart());
    }

    @Test
    void solveFirstPart() {
        assertEquals(1535, sut.solveFirstPart());
    }

    @Test
    void solveSecondPart_withSampleInput() {
        doReturn(Arrays.stream("""
                .......S.......
                ...............
                .......^.......
                ...............
                ......^.^......
                ...............
                .....^.^.^.....
                ...............
                ....^.^...^....
                ...............
                ...^.^...^.^...
                ...............
                ..^...^.....^..
                ...............
                .^.^.^.^.^...^.
                ...............
                """.split("\n")).collect(Collectors.toCollection(ArrayList::new))).when(sut).loadInput();
        assertEquals(40, sut.solveSecondPart());
    }

    @Test
    void solveSecondPart() {
        assertEquals(4404709551015L, sut.solveSecondPart());
    }
}